name: Release Module

on:
  push:
    tags:
      - '*-v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Parse tag
        id: parse
        run: |
          TAG="${GITEA_REF#refs/tags/}"
          MODULE="${TAG%-v*}"
          VERSION="${TAG#${MODULE}-}"
          echo "module=${MODULE}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Releasing ${MODULE} at ${VERSION}"

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ gitea.actor }}
          password: ${{ gitea.token }}

      - name: Package and Push
        uses: eunanio/nori/action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          repository: ${{ gitea.repository }}/${{ steps.parse.outputs.module }}
          tag: ${{ steps.parse.outputs.version }}
          module-path: ./modules/${{ steps.parse.outputs.module }}
          description: "Terraform ${{ steps.parse.outputs.module }} module"

